export const meiDataTypes = {
  "MEI dev": {
    apiIds: ["meidev"],
    hash: "",
    link: "",
    format: "MEI",
    version: "",
    customization: "",
  },
  "MEI 4.0.1": {
    apiIds: ["mei401", "c-mei-all"],
    hash: "",
    link: "",
    format: "MEI",
    version: "4.0.1",
    customization: "",
  },
  "MEI 4.0.1 All anyStart": {
    apiIds: ["mei401-any", "c-mei-all-any"],
    hash: "",
    link: "",
    format: "MEI",
    version: "4.0.1",
    customization: "",
  },
  "MEI 4.0.1 CMN": {
    apiIds: ["mei401-cmn", "c-mei-cmn"],
    hash: "",
    link: "",
    format: "MEI",
    version: "4.0.1",
    customization: "CMN",
  },
  "MEI 4.0.1 Mensural": {
    apiIds: ["mei401-mensural", "c-mei-mensural"],
    hash: "",
    link: "",
    format: "MEI",
    version: "4.0.1",
    customization: "Mensural",
  },
  "MEI 4.0.1 Neumes": {
    apiIds: ["mei401-neumes", "c-mei-neumes"],
    hash: "",
    link: "",
    format: "MEI",
    version: "4.0.1",
    customization: "Neumes",
  },
  "MEI 4.0.0": {
    apiIds: ["mei400"],
    hash: "",
    link: "",
    format: "MEI",
    version: "4.0.0",
    customization: "",
  },
  "MEI 3.0.0": {
    apiIds: ["mei300"],
    hash: "",
    link: "",
    format: "MEI",
    version: "3.0.0",
    customization: "",
  },
  "MEI 2.1.1": {
    apiIds: ["mei211"],
    hash: "",
    link: "",
    format: "MEI",
    version: "2.1.1",
    customization: "",
  },
  "MEI 2.0.0": {
    apiIds: ["mei200"],
    hash: "",
    link: "",
    format: "MEI",
    version: "2.0.0",
    customization: "",
  },
  "MEI 1.0.0": {
    apiIds: ["mei100"],
    hash: "",
    link: "",
    format: "MEI",
    version: "1.0.0",
    customization: "",
  },
};
