name: Docker

on:
  push:
    branches: [ main, dev ]
    tags:     [ v* ]
  pull_request:
    branches: [ main, dev ]

jobs:

  docker:
    name: build the Docker image
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # use the current user to log into the 
      # GitHub container registry 
      - name: Log in to GitHub Container registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      # Login against DockerHub registry except on PR
      - name: Log in to DockerHub
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v2
        with:
          username: vifebot
          password: ${{ secrets.VIFEBOT_DOCKERHUB_TOKEN }}
          
      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            edirom/vife-meigarage-webclient
          flavor: |
            latest=${{ github.ref == 'refs/heads/main' }}
            
      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      # on main branch dont set Docker build ARG
      - name: Build and push Docker image
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}         
      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      # on main set Docker build ARG to use dev webservice
      - name: Build and push Docker image
        if: ${{ github.ref == 'refs/heads/dev' }}
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VUE_APP_WEBSERVICE_URL=https://dev.meigarage.edirom.de/ege-webservice/
